//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Client_Prob = new HashSet<Client_Prob>();
            this.LocationTabs = new HashSet<LocationTab>();
        }
    
        public int IdClient { get; set; }
        public string email { get; set; }
        public Nullable<int> telephone { get; set; }
        public string adresse { get; set; }
        public Nullable<int> age { get; set; }
        public string statutSociale { get; set; }
        public string image { get; set; }
        public string prenom_ { get; set; }
        public string nom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_Prob> Client_Prob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationTab> LocationTabs { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
