//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationTab
    {
        public int IdCommande { get; set; }
        public Nullable<int> IdP { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdVoiture { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Proprietaire Proprietaire { get; set; }
        public virtual Voiture Voiture { get; set; }
    }
}
